### ISSUE TITLE
Adding plugin fails unless you have node-xcode installed

### ISSUE THREAD

**Issue by kimosabi77** [Justin-Credible/cordova-plugin-braintree#20]
I was getting an error installing the plugin for ios.

Line 111:30  if(!frameworkFilesToEmbed.length) return;
cannot read property length of undefined

To fix that, install node-xcode as per http://stackoverflow.com/a/36723619

npm i https://github.com/alunny/node-xcode.git --save

**Comment by kimosabi77** [comment]
actually, I've removed the ios platform, and the plugin, reinstalled and I now get this.  So it seems that node-xcode does not fix it.

```
Failed to install 'cordova-plugin-braintree':TypeError: Cannot read property 'length' of undefined
    at module.exports (/Users/kimrichardson/Apps/Ionic/WashPayProduction/plugins/cordova-plugin-braintree/hooks/add_embedded_ios_frameworks.js:111:30)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
```

```
$ node -v
v4.4.7

$ cordova -v
6.4.0
```

**Comment by Taracque** [comment]
Have you tried 
`npm i xcode`

My setup is the  following:
node -v
v4.6.2
cordova -v
6.4.0
npm list | grep xcode
├─┬ xcode@0.8.9

**Comment by kimosabi77** [comment]
Thanks,  I installed your fork and am good now.

**Comment by Justin-Credible** [comment]
The latest version of the plugin installs node-xcode during plugin add, so this should be resolved.
