### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by hussainak** [Justin-Credible/cordova-plugin-braintree#21]
Hi @Justin-Credible 

I am getting the following error while installing the plugin, seen it before?

```
cordova plugin add cordova-plugin-braintree --save
Installing "cordova-plugin-braintree" for android
no dir  anjtanSchoo/Plugins/cordova-plugin-braintree
Failed to install 'cordova-plugin-braintree':TypeError: Cannot read property 'length' of undefined
    at module.exports (/Users/ali/Desktop/Development/IonicApps/sundaysmsionicapp/plugins/cordova-plugin-braintree/hooks/add_embedded_ios_frameworks.js:111:30)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Error: Cannot read property 'length' of undefined
```

**Comment by francescofiori** [comment]
@hussainak same error for me using v0.5.1

**Comment by hussainak** [comment]
@francescofiori I am using @Taracque fork, see #16
